exp_name: Base
describe: CUB-R50-BASE
data:
  name: cub
  path: 'data/CUB_200_2011'
#  path: '/home/ming/data/fine-grained-data/CUB_200_2011'
#  name: car
#  path: '/home/ming/data/fine-grained-data/Stanford_Cars'

  trans_name: 'default'
  trans_params:
    scale_size: 512
    crop_size: 448

  split_train: false
  n_splits: 5
  used_split_id: 0
  used_cache: false

loader:
  batch_size: 16
  num_workers: 8

model:
  name: base
  monitor_value: best_acc

  sync_bn: false
  unuse_p: false
  val_step: 1

  resume: null

  network:
    backbone:
      name: resnet
      model_type: 50


  # optim related
  max_epochs: &max_epochs 100

  optim:
    no_bias_decay: false
    lr:
      - 0.002
      - 0.02
    weight_decay:
      - 5.0e-4
      - 1.0e-4
    scheduler:
      name: cosine
      params:
        warmup_size: 10
        delay: 0
        t_0: *max_epochs
        t_multi: 1
gpu_ids: '0,1,2,3,'