from .build_cfg import CfgNode as CN
from .build_cfg import Updater as UD

# default data config
_DATA_CFG_DICT = CN()
_DATA_CFG_DICT.CUB = CN()
_DATA_CFG_DICT.CUB.DATA = CN()
_DATA_CFG_DICT.CUB.DATA.NAME = "CUB"
_DATA_CFG_DICT.CUB.DATA.INPUT = CN()
_DATA_CFG_DICT.CUB.DATA.INPUT.SIZE_SCALE = (600, 600)
_DATA_CFG_DICT.CUB.DATA.PATH = "data/fine-grained-data/CUB_200_2011"

_DATA_CFG_DICT.CAR = CN()
_DATA_CFG_DICT.CAR.DATA = CN()
_DATA_CFG_DICT.CAR.DATA.NAME = "CAR"
_DATA_CFG_DICT.CAR.DATA.INPUT = CN()
_DATA_CFG_DICT.CAR.DATA.INPUT.SIZE_SCALE = 600,
_DATA_CFG_DICT.CAR.DATA.PATH = "data/fine-grained-data/Stanford_Cars"

_DATA_CFG_DICT.DOG = CN()
_DATA_CFG_DICT.DOG.DATA = CN()
_DATA_CFG_DICT.DOG.DATA.NAME = "DOG"
_DATA_CFG_DICT.DOG.DATA.INPUT = CN()
_DATA_CFG_DICT.DOG.DATA.INPUT.SIZE_SCALE = 600,
_DATA_CFG_DICT.DOG.DATA.PATH = "data/fine-grained-data/Stanford_Dogs"

_DATA_CFG_DICT.AIR = CN()
_DATA_CFG_DICT.AIR.DATA = CN()
_DATA_CFG_DICT.AIR.DATA.NAME = "AIR"
_DATA_CFG_DICT.AIR.DATA.INPUT = CN()
_DATA_CFG_DICT.AIR.DATA.INPUT.SIZE_SCALE = 600,
_DATA_CFG_DICT.AIR.DATA.PATH = "data/fine-grained-data/fgvc-aircraft-2013b"

# for training
_C = CN()
_U = UD()

_C.DATA = CN()
_C.DATA.NAME = ""
_C.DATA.PATH = ""
_C.DATA.INPUT = CN()
_C.DATA.INPUT.SIZE_SCALE = (600, 600)
_C.DATA.INPUT.SIZE_IMAGE = 448
_C.DATA.INPUT.TRANS_NAME = 'DEFAULT'

_C.DATA.DATASET = CN()

_C.DATA.DATASET.CACHED = False

_C.DATA.DATASET.SPLIT_TRAIN = False
_C.DATA.DATASET.N_SPLIT = 5
_C.DATA.DATASET.USED_SPLIT_ID = 0

_C.DATA.DATASET.FEW_SHOT = CN()
_C.DATA.DATASET.FEW_SHOT.ENABLED = False
_C.DATA.DATASET.FEW_SHOT.TRAIN_SHOT = -1
_C.DATA.DATASET.FEW_SHOT.VALID_SHOT = -1

_C.DATA.DATALOADER = CN()
_C.DATA.DATALOADER.SAMPLER_TRAIN = "DEFAULT"  # "DEFAULT", "FEW-SHOT"

_C.DATA.DATALOADER.BATCH_SIZE = 16
_C.DATA.DATALOADER.NUM_WORKERS = 4
_C.DATA.DATALOADER.VALID_SCALE = 1.0

_C.TRAINER = CN()
_C.TRAINER.MONITOR_VALUE = "BEST_ACC"
_C.TRAINER.SYNC_BN = False
_C.TRAINER.UNUSED_PARAMETERS = False
_C.TRAINER.VALID_INTERVAL = 1
_C.TRAINER.MAX_EPOCHS = 200

_C.TRAINER.DEVICE = "gpu"
_C.TRAINER.DEVICE_ID = 0,

_C.TRAINER.RESUME = None

_C.MODEL = CN()
_C.MODEL.RESUME = None

_C.MODEL.NET = CN()
_C.MODEL.NET.VARIANT = 'default'
_C.MODEL.NET.DATA_EFFICIENT = False
_C.MODEL.NET.BACKBONE = CN()
_C.MODEL.NET.BACKBONE.NAME = "ViT-B/16"

# vit backbone
_C.MODEL.NET.BACKBONE.STRIDE_SIZE = 16
_C.MODEL.NET.BACKBONE.IMAGE_SIZE = _C.DATA.INPUT.SIZE_IMAGE
_U.set_dependent('MODEL.NET.BACKBONE.IMAGE_SIZE', 'DATA.INPUT.SIZE_IMAGE')
_C.MODEL.NET.BACKBONE.FEAT_DIM = 2048

# cnn backbone
_C.MODEL.NET.BACKBONE.LAST_STRIDE = 1
_C.MODEL.NET.BACKBONE.VISUAL_PROMPT = False
# there is only one network for the text encoder
_C.MODEL.NET.PROMPTS = CN()
_C.MODEL.NET.PROMPTS.TYPE = 'BASE'
_C.MODEL.NET.PROMPTS.DATA_NAME = ""
_U.set_dependent('MODEL.NET.PROMPTS.DATA_NAME', 'DATA.NAME')

_C.MODEL.OPTIM = CN()
_C.MODEL.OPTIM.MAX_EPOCHS = 0
_U.set_dependent('MODEL.OPTIM.MAX_EPOCHS', 'TRAINER.MAX_EPOCHS')
_C.MODEL.OPTIM.NO_BIAS_DECAY = False
_C.MODEL.OPTIM.LR = [0.02, 0.02,]
_C.MODEL.OPTIM.WEIGHT_DECAY = [0.0, 0.0]
_C.MODEL.OPTIM.MOMENTUM = [0.9, 0.9]

_C.MODEL.SCHED = CN()
_C.MODEL.SCHED.WARMUP = CN()
_C.MODEL.SCHED.WARMUP.MODE = 'constant'  # choose from ['constant', 'linear']
_C.MODEL.SCHED.WARMUP.SIZE = 1
_C.MODEL.SCHED.WARMUP.VALUE = 1.0e-5  # used for constant
_C.MODEL.SCHED.WARMUP.MIN_VALUE = 1.0e-5  # used for linear

_C.MODEL.SCHED.NAME = 'COSINE'
_C.MODEL.SCHED.STEP = CN()
_C.MODEL.SCHED.STEP.STEP_SIZE = 30
_C.MODEL.SCHED.STEP.GAMMA = 0.1
_C.MODEL.SCHED.STEP.LAST_EPOCH = -1
_C.MODEL.SCHED.STEP.VERBOSE = False
_C.MODEL.SCHED.STEP.DELAY = 0

_C.MODEL.SCHED.MILES = CN()
_C.MODEL.SCHED.MILES.MILESTONES = [30, 60, 90]
_C.MODEL.SCHED.MILES.GAMMA = 0.1
_C.MODEL.SCHED.MILES.LAST_EPOCH = -1
_C.MODEL.SCHED.MILES.VERBOSE = False
_C.MODEL.SCHED.MILES.DELAY = 0

_C.MODEL.SCHED.COSINE = CN()
_C.MODEL.SCHED.COSINE.T_0 = 0
_U.set_dependent('MODEL.SCHED.COSINE.T_0', 'TRAINER.MAX_EPOCHS')
_C.MODEL.SCHED.COSINE.T_MULTI = 1
_C.MODEL.SCHED.COSINE.DELAY = 0
_C.MODEL.SCHED.COSINE.LAST_EPOCH = -1
_C.MODEL.SCHED.COSINE.VERBOSE = False

